version: '2.0'

services:
  api: 
    container_name: api
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_HOST: database

  database:
    container_name: db
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"